Whenever I try to run lines 78-82 in my table creation .py file, I receive a "timed out" errror.
